# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'theMovieDB' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for theMovieDB
  pod 'Alamofire', '5.5.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'theMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'theMovieDBUITests' do
    # Pods for testing
  end

end
