# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

use_frameworks!
inhibit_all_warnings!

workspace 'theMovieDB.xcworkspace'

def commonPods
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
end

def dataPods
  pod 'Alamofire', '5.5.0'
end

def appPods
  dataPods
  commonPods
  pod 'Kingfisher', '~> 7.0'
end

# Defining Pods for the modules
target 'theMovieDB' do
  # Pods for theMovieDB
  appPods

  target 'Data' do
    project 'Data/Data'
    inherit! :search_paths
#    commonPods
#    dataPods
    
    target 'DataTests' do
      inherit! :search_paths
      appPods
    end
    
  end

  target 'Domain' do
    project 'Domain/Domain'
    inherit! :search_paths
#    commonPods
    
    target 'DomainTests' do
      inherit! :search_paths
      appPods
    end
    
  end
  
  # Pods for testing
  target 'theMovieDBTests' do
    inherit! :search_paths
    appPods
  end

end
